mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
